# Criado por José Eduardo Santana Martins
# Este arquivo serve para criar a opção "Liberar todas as competências" no contrato.
"""contratos liberar todas as competencias

Revision ID: 2183de7ec74a
Revises: e5b8c3d7a921
Create Date: 2026-10-02 18:28:26.654600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2183de7ec74a'
down_revision: Union[str, Sequence[str], None] = 'e5b8c3d7a921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('liberar_todas_competencias', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'liberar_todas_competencias')
    # ### end Alembic commands ###
