# Criado por José Eduardo Santana Martins
# Este arquivo serve para ampliar o preço unitário dos itens (contrato, medição, reajuste e aditamento) para 4 casas decimais.
"""contratos: valor unitário com 4 casas decimais (ex.: R$ 0,075 por página)

Só amplia as colunas (18,2 → 18,4): nenhum valor muda. Os totais em reais continuam com 2 casas.
O downgrade arredonda os preços para 2 casas.

Revision ID: 3f23277d8a5a
Revises: 11d8a496ccab
Create Date: 2026-10-01 17:55:59.095627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f23277d8a5a'
down_revision: Union[str, Sequence[str], None] = '11d8a496ccab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos_alteracoes_itens', 'valor_unitario',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('contratos_competencias_itens', 'valor_unitario',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('contratos_itens', 'valor_unitario',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('contratos_reajustes_itens', 'valor_unitario_atual',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('contratos_reajustes_itens', 'valor_referencial',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('contratos_reajustes_itens', 'valor_unitario_reajustado',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos_reajustes_itens', 'valor_unitario_reajustado',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('contratos_reajustes_itens', 'valor_referencial',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('contratos_reajustes_itens', 'valor_unitario_atual',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('contratos_itens', 'valor_unitario',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('contratos_competencias_itens', 'valor_unitario',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('contratos_alteracoes_itens', 'valor_unitario',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
