# Criado por José Eduardo Santana Martins
# Este arquivo serve para criar favoritos, mural de parabéns e as colunas de foto e opt-out de aniversário no usuário.
"""diretorio_ramais_aniversariantes

Revision ID: 44f539651816
Revises: 5bf9f2139d6e
Create Date: 2026-10-03 22:14:18.241522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f539651816'
down_revision: Union[str, Sequence[str], None] = '5bf9f2139d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diretorio_favoritos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('favorito_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['favorito_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'favorito_id')
    )
    op.create_table('diretorio_parabens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aniversariante_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('autor_nome', sa.String(length=200), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aniversariante_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aniversariante_id', 'autor_id', 'ano', name='uq_diretorio_parabens_autor_ano')
    )
    op.create_index(op.f('ix_diretorio_parabens_aniversariante_id'), 'diretorio_parabens', ['aniversariante_id'], unique=False)
    op.add_column('usuarios', sa.Column('foto_anexo_id', sa.Uuid(), nullable=True))
    op.add_column('usuarios', sa.Column('foto_origem', sa.String(length=10), nullable=True))
    op.add_column('usuarios', sa.Column('ocultar_aniversario', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key('fk_usuarios_foto_anexo_id', 'usuarios', 'anexos', ['foto_anexo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuarios_foto_anexo_id', 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'ocultar_aniversario')
    op.drop_column('usuarios', 'foto_origem')
    op.drop_column('usuarios', 'foto_anexo_id')
    op.drop_index(op.f('ix_diretorio_parabens_aniversariante_id'), table_name='diretorio_parabens')
    op.drop_table('diretorio_parabens')
    op.drop_table('diretorio_favoritos')
    # ### end Alembic commands ###
