"""módulo de contratos: empresas, prepostos, contratos, itens, equipe e documentos (MVP 1)

Revision ID: 47a98027b841
Revises: b2d4f6a8c0e1
Create Date: 2026-09-24 02:25:41.479050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a98027b841'
down_revision: Union[str, Sequence[str], None] = 'b2d4f6a8c0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos_empresas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=250), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=250), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('contratos_empresas_prepostos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['contratos_empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'cpf')
    )
    op.create_index(op.f('ix_contratos_empresas_prepostos_empresa_id'), 'contratos_empresas_prepostos', ['empresa_id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequencial', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('apelido', sa.String(length=200), nullable=False),
    sa.Column('objeto', sa.String(length=4000), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('vigencia_inicial_meses', sa.Integer(), nullable=False),
    sa.Column('vigencia_maxima_meses', sa.Integer(), nullable=False),
    sa.Column('periodicidade_meses', sa.Integer(), nullable=False),
    sa.Column('mes_reajuste', sa.Integer(), nullable=False),
    sa.Column('sei_gestao_numero', sa.String(length=100), nullable=False),
    sa.Column('sei_gestao_link', sa.String(length=1000), nullable=False),
    sa.Column('sei_execucao_numero', sa.String(length=100), nullable=False),
    sa.Column('sei_execucao_link', sa.String(length=1000), nullable=False),
    sa.Column('situacao_forcada', sa.String(length=20), nullable=True),
    sa.Column('valor_global_reajustado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("situacao_forcada IS NULL OR situacao_forcada IN ('ativo', 'a_vencer', 'encerrado', 'suspenso')", name='ck_contratos_situacao_forcada'),
    sa.CheckConstraint('mes_reajuste BETWEEN 1 AND 12', name='ck_contratos_mes_reajuste'),
    sa.CheckConstraint('periodicidade_meses IN (1, 2, 3, 6, 12)', name='ck_contratos_periodicidade'),
    sa.CheckConstraint('vigencia_inicial_meses > 0', name='ck_contratos_vigencia_inicial'),
    sa.CheckConstraint('vigencia_maxima_meses >= vigencia_inicial_meses', name='ck_contratos_vigencia_maxima'),
    sa.ForeignKeyConstraint(['criador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['contratos_empresas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequencial', 'ano')
    )
    op.create_index(op.f('ix_contratos_empresa_id'), 'contratos', ['empresa_id'], unique=False)
    op.create_table('contratos_documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_tipo', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('anexo_id', sa.Uuid(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anexo_id'], ['anexos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'codigo_tipo')
    )
    op.create_index(op.f('ix_contratos_documentos_anexo_id'), 'contratos_documentos', ['anexo_id'], unique=False)
    op.create_index(op.f('ix_contratos_documentos_contrato_id'), 'contratos_documentos', ['contrato_id'], unique=False)
    op.create_table('contratos_equipe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=40), nullable=False),
    sa.Column('nome_usuario', sa.String(length=250), nullable=False),
    sa.Column('valido_de', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valido_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("papel IN ('gestor', 'gestor_suplente', 'fiscal_administrativo', 'fiscal_administrativo_suplente', 'fiscal_tecnico', 'fiscal_tecnico_suplente')", name='ck_contratos_equipe_papel'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'usuario_id', 'papel')
    )
    op.create_index(op.f('ix_contratos_equipe_contrato_id'), 'contratos_equipe', ['contrato_id'], unique=False)
    op.create_index(op.f('ix_contratos_equipe_usuario_id'), 'contratos_equipe', ['usuario_id'], unique=False)
    op.create_table('contratos_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('calcula_pro_rata', sa.Boolean(), nullable=False),
    sa.Column('codigo_classe', sa.String(length=80), nullable=False),
    sa.Column('codigo_natureza_despesa', sa.String(length=80), nullable=False),
    sa.Column('codigo_siafisico', sa.String(length=80), nullable=False),
    sa.Column('codigo_catmat_catser', sa.String(length=80), nullable=False),
    sa.Column('quantidade_mensal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantidade_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantidade_executada', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('continuo', 'sob_demanda')", name='ck_contratos_itens_tipo'),
    sa.CheckConstraint('valor_unitario >= 0', name='ck_contratos_itens_valor_unitario'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_itens_contrato_id'), 'contratos_itens', ['contrato_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratos_itens_contrato_id'), table_name='contratos_itens')
    op.drop_table('contratos_itens')
    op.drop_index(op.f('ix_contratos_equipe_usuario_id'), table_name='contratos_equipe')
    op.drop_index(op.f('ix_contratos_equipe_contrato_id'), table_name='contratos_equipe')
    op.drop_table('contratos_equipe')
    op.drop_index(op.f('ix_contratos_documentos_contrato_id'), table_name='contratos_documentos')
    op.drop_index(op.f('ix_contratos_documentos_anexo_id'), table_name='contratos_documentos')
    op.drop_table('contratos_documentos')
    op.drop_index(op.f('ix_contratos_empresa_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_contratos_empresas_prepostos_empresa_id'), table_name='contratos_empresas_prepostos')
    op.drop_table('contratos_empresas_prepostos')
    op.drop_table('contratos_empresas')
    # ### end Alembic commands ###
