# Criado por José Eduardo Santana Martins
# Este arquivo serve para criar as tabelas de correção de itens, o histórico dos itens e a versão sincronizada das competências.
"""correcoes de itens e historico dos itens

Revision ID: 5bf9f2139d6e
Revises: dd7999d97284
Create Date: 2026-10-02 22:28:46.017113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bf9f2139d6e'
down_revision: Union[str, Sequence[str], None] = 'dd7999d97284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos_correcoes_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('autor_nome', sa.String(length=250), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('mudancas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('previa', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('situacao', sa.String(length=12), nullable=False),
    sa.Column('decidido_por_id', sa.Integer(), nullable=True),
    sa.Column('decidido_por_nome', sa.String(length=250), nullable=False),
    sa.Column('decidido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_decisao', sa.Text(), nullable=False),
    sa.Column('versao_cadastro', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("situacao IN ('pendente', 'aplicada', 'recusada', 'cancelada')", name='ck_contratos_correcoes_situacao'),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_correcoes_itens_contrato_id'), 'contratos_correcoes_itens', ['contrato_id'], unique=False)
    op.create_table('contratos_itens_historico',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('descricao_item', sa.String(length=1000), nullable=False),
    sa.Column('versao_cadastro', sa.Integer(), nullable=False),
    sa.Column('correcao_id', sa.Uuid(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('autor_nome', sa.String(length=250), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('campos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['correcao_id'], ['contratos_correcoes_itens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['contratos_itens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_itens_historico_contrato_id'), 'contratos_itens_historico', ['contrato_id'], unique=False)
    op.create_index(op.f('ix_contratos_itens_historico_item_id'), 'contratos_itens_historico', ['item_id'], unique=False)
    op.add_column('contratos_competencias', sa.Column('versao_cadastro_sincronizada', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos_competencias', 'versao_cadastro_sincronizada')
    op.drop_index(op.f('ix_contratos_itens_historico_item_id'), table_name='contratos_itens_historico')
    op.drop_index(op.f('ix_contratos_itens_historico_contrato_id'), table_name='contratos_itens_historico')
    op.drop_table('contratos_itens_historico')
    op.drop_index(op.f('ix_contratos_correcoes_itens_contrato_id'), table_name='contratos_correcoes_itens')
    op.drop_table('contratos_correcoes_itens')
    # ### end Alembic commands ###
