# Criado por José Eduardo Santana Martins
# Este arquivo serve para criar as tabelas de orçamento, execução, prorrogação, reajuste e aditamento dos contratos.
"""módulo de contratos: orçamento, execução, avaliação, prorrogação, reajuste, aditamento/supressão e modelos (MVPs 2 a 8)

Gerada pelo `alembic revision --autogenerate` a partir dos modelos e revisada à mão. Cria todas as
tabelas do dia a dia do contrato: previsão e NEs, checklists e formulários, competências e seus
registros por etapa, prorrogação, reajuste, aditamento/supressão e modelos globais.

Revision ID: 65c4a5320944
Revises: 47a98027b841
Create Date: 2026-09-24 02:54:35.467773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65c4a5320944'
down_revision: Union[str, Sequence[str], None] = '47a98027b841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Cria as tabelas; as que dependem de outras vêm depois delas."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Modelos globais de checklist e de formulário
    op.create_table('contratos_modelos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('conteudo', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('checklist', 'formulario')", name='ck_contratos_modelos_tipo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_modelos_tipo'), 'contratos_modelos', ['tipo'], unique=False)
    # Aditamento/supressão (cabeçalho do processo)
    op.create_table('contratos_alteracoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('situacao', sa.String(length=30), nullable=False),
    sa.Column('sequencia_vigencia', sa.Integer(), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fim', sa.Date(), nullable=False),
    sa.Column('mes_efeito', sa.Date(), nullable=False),
    sa.Column('valor_global_original', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('impacto_valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('impacto_percentual', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('justificativa_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('autorizacao_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('de_acordo_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('termo_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('memoria_pdf_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('memoria_xlsx_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('consolidado_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("situacao IN ('rascunho', 'aguardando_ciencias', 'concluida', 'cancelada')", name='ck_contratos_alteracoes_situacao'),
    sa.CheckConstraint("tipo IN ('aditamento', 'supressao')", name='ck_contratos_alteracoes_tipo'),
    sa.ForeignKeyConstraint(['autorizacao_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consolidado_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['de_acordo_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['justificativa_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['memoria_pdf_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['memoria_xlsx_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['termo_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_alteracoes_contrato_id'), 'contratos_alteracoes', ['contrato_id'], unique=False)
    op.create_index('ux_contratos_alteracoes_em_andamento', 'contratos_alteracoes', ['contrato_id'], unique=True, postgresql_where=sa.text("situacao IN ('rascunho', 'aguardando_ciencias')"))
    # Versões do checklist do contrato
    op.create_table('contratos_checklists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_nome', sa.String(length=250), nullable=False),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'versao')
    )
    op.create_index(op.f('ix_contratos_checklists_contrato_id'), 'contratos_checklists', ['contrato_id'], unique=False)
    # Competências de execução (dados de cada etapa na própria linha)
    op.create_table('contratos_competencias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('sequencia_vigencia', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fim', sa.Date(), nullable=False),
    sa.Column('etapa_atual', sa.String(length=20), nullable=False),
    sa.Column('medicao_iniciada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('medicao_concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nf_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('nf_numero', sa.String(length=100), nullable=False),
    sa.Column('nf_recebida_em', sa.Date(), nullable=True),
    sa.Column('prazo_pagamento_dias', sa.Integer(), nullable=True),
    sa.Column('origem_valor_nf', sa.String(length=20), nullable=True),
    sa.Column('nf_valor_bruto', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('nf_retencao_ir', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_retencao_inss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_retencao_iss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_retencao_pis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_retencao_cofins', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_adicional_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('nf_adicional_numero', sa.String(length=100), nullable=False),
    sa.Column('nf_adicional_valor_bruto', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('nf_adicional_retencao_ir', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_adicional_retencao_inss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_adicional_retencao_iss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_adicional_retencao_pis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_adicional_retencao_cofins', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nf_concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consolidado_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('consolidado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ob_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('ob_enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("etapa_atual IN ('medicao', 'avaliacao', 'nota_fiscal', 'cadin', 'checklist', 'consolidado', 'ordem_bancaria', 'concluida')", name='ck_contratos_competencias_etapa'),
    sa.CheckConstraint("origem_valor_nf IS NULL OR origem_valor_nf IN ('medicao', 'manual')", name='ck_contratos_competencias_origem_nf'),
    sa.ForeignKeyConstraint(['consolidado_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nf_adicional_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nf_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ob_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'periodo_inicio')
    )
    op.create_index(op.f('ix_contratos_competencias_contrato_id'), 'contratos_competencias', ['contrato_id'], unique=False)
    # Versões do formulário de avaliação
    op.create_table('contratos_formularios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('definicao', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_nome', sa.String(length=250), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'versao')
    )
    op.create_index(op.f('ix_contratos_formularios_contrato_id'), 'contratos_formularios', ['contrato_id'], unique=False)
    # Notas de Empenho
    op.create_table('contratos_notas_empenho',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'numero')
    )
    op.create_index(op.f('ix_contratos_notas_empenho_contrato_id'), 'contratos_notas_empenho', ['contrato_id'], unique=False)
    # Previsão orçamentária por vigência
    op.create_table('contratos_previsoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('sequencia_vigencia', sa.Integer(), nullable=False),
    sa.Column('salva', sa.Boolean(), nullable=False),
    sa.Column('salva_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('salva_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salva_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'sequencia_vigencia')
    )
    op.create_index(op.f('ix_contratos_previsoes_contrato_id'), 'contratos_previsoes', ['contrato_id'], unique=False)
    # Prorrogações registradas (termos aditivos)
    op.create_table('contratos_prorrogacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('meses', sa.Integer(), nullable=False),
    sa.Column('assinada_em', sa.Date(), nullable=False),
    sa.Column('numero_termo', sa.String(length=100), nullable=False),
    sa.Column('fim_anterior', sa.Date(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('anexo_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_documento', sa.Integer(), nullable=True),
    sa.Column('relatorio_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relatorio_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'data_inicio')
    )
    op.create_index(op.f('ix_contratos_prorrogacoes_contrato_id'), 'contratos_prorrogacoes', ['contrato_id'], unique=False)
    # Reajustes
    op.create_table('contratos_reajustes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('sequencia_vigencia', sa.Integer(), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fim', sa.Date(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('base_atual', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_reajustada', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_global_atual', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_global_reajustado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('evidencia_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('apostilamento_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("situacao IN ('rascunho', 'concluido', 'cancelado')", name='ck_contratos_reajustes_situacao'),
    sa.ForeignKeyConstraint(['apostilamento_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidencia_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_reajustes_contrato_id'), 'contratos_reajustes', ['contrato_id'], unique=False)
    op.create_index('ux_contratos_reajustes_rascunho', 'contratos_reajustes', ['contrato_id'], unique=True, postgresql_where=sa.text("situacao = 'rascunho'"))
    # Ciências e itens do aditamento/supressão
    op.create_table('contratos_alteracoes_ciencias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alteracao_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('papel', sa.String(length=40), nullable=False),
    sa.Column('registrada_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alteracao_id'], ['contratos_alteracoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alteracao_id', 'usuario_id')
    )
    op.create_index(op.f('ix_contratos_alteracoes_ciencias_alteracao_id'), 'contratos_alteracoes_ciencias', ['alteracao_id'], unique=False)
    op.create_table('contratos_alteracoes_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alteracao_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantidade_original', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantidade_nova', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantidade_executada', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('impacto_valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['alteracao_id'], ['contratos_alteracoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['contratos_itens.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alteracao_id', 'item_id')
    )
    op.create_index(op.f('ix_contratos_alteracoes_itens_alteracao_id'), 'contratos_alteracoes_itens', ['alteracao_id'], unique=False)
    op.create_index(op.f('ix_contratos_alteracoes_itens_item_id'), 'contratos_alteracoes_itens', ['item_id'], unique=False)
    # Documentos de cada versão do checklist
    op.create_table('contratos_checklists_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('checklist_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('observacao', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['contratos_checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_checklists_itens_checklist_id'), 'contratos_checklists_itens', ['checklist_id'], unique=False)
    # Avaliação da competência (etapa 2)
    op.create_table('contratos_competencias_avaliacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competencia_id', sa.Uuid(), nullable=False),
    sa.Column('formulario_id', sa.Uuid(), nullable=True),
    sa.Column('definicao', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('respostas_iniciais', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('avaliador_inicial_id', sa.Integer(), nullable=True),
    sa.Column('avaliacao_inicial_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('respostas_gestor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('complemento_gestor', sa.String(length=4000), nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('avaliacao_gestor_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assinaturas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('assinaturas_definidas_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_gerado_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('pdf_assinado_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconsideracoes', sa.Integer(), nullable=False),
    sa.Column('reconsideracao_anexo_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['avaliador_inicial_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competencia_id'], ['contratos_competencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gestor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pdf_assinado_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pdf_gerado_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reconsideracao_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia_id')
    )
    # Consultas ao CADIN (etapa 4)
    op.create_table('contratos_competencias_cadin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competencia_id', sa.Uuid(), nullable=False),
    sa.Column('possui_pendencia', sa.Boolean(), nullable=False),
    sa.Column('pendencia', sa.String(length=2000), nullable=False),
    sa.Column('texto_notificacao', sa.String(length=2500), nullable=False),
    sa.Column('certidao_anexo_id', sa.Uuid(), nullable=False),
    sa.Column('email_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_nome', sa.String(length=250), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certidao_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['competencia_id'], ['contratos_competencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_competencias_cadin_competencia_id'), 'contratos_competencias_cadin', ['competencia_id'], unique=False)
    # Ciências da medição (etapa 1)
    op.create_table('contratos_competencias_ciencias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competencia_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('papel', sa.String(length=40), nullable=False),
    sa.Column('registrada_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competencia_id'], ['contratos_competencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia_id', 'usuario_id')
    )
    op.create_index(op.f('ix_contratos_competencias_ciencias_competencia_id'), 'contratos_competencias_ciencias', ['competencia_id'], unique=False)
    # Documentos do checklist mensal copiados para a competência (etapa 5)
    op.create_table('contratos_competencias_documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competencia_id', sa.Uuid(), nullable=False),
    sa.Column('checklist_id', sa.Uuid(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('observacao', sa.String(length=1000), nullable=False),
    sa.Column('anexo_id', sa.Uuid(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['competencia_id'], ['contratos_competencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia_id', 'ordem')
    )
    op.create_index(op.f('ix_contratos_competencias_documentos_competencia_id'), 'contratos_competencias_documentos', ['competencia_id'], unique=False)
    # Itens medidos na competência (fotografia dos itens do contrato)
    op.create_table('contratos_competencias_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competencia_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('calcula_pro_rata', sa.Boolean(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fator_meses', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quantidade_prevista', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantidade_medida', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.ForeignKeyConstraint(['competencia_id'], ['contratos_competencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['contratos_itens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia_id', 'item_id')
    )
    op.create_index(op.f('ix_contratos_competencias_itens_competencia_id'), 'contratos_competencias_itens', ['competencia_id'], unique=False)
    op.create_index(op.f('ix_contratos_competencias_itens_item_id'), 'contratos_competencias_itens', ['item_id'], unique=False)
    # Memórias de cálculo da medição (PDF versionado)
    op.create_table('contratos_competencias_memorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competencia_id', sa.Uuid(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('anexo_id', sa.Uuid(), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['competencia_id'], ['contratos_competencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia_id', 'versao')
    )
    op.create_index(op.f('ix_contratos_competencias_memorias_competencia_id'), 'contratos_competencias_memorias', ['competencia_id'], unique=False)
    # NEs escolhidas na medição, em ordem de consumo
    op.create_table('contratos_competencias_notas',
    sa.Column('competencia_id', sa.Uuid(), nullable=False),
    sa.Column('nota_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competencia_id'], ['contratos_competencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nota_id'], ['contratos_notas_empenho.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('competencia_id', 'nota_id')
    )
    op.create_index(op.f('ix_contratos_competencias_notas_nota_id'), 'contratos_competencias_notas', ['nota_id'], unique=False)
    # Extrato das NEs (pagamentos)
    op.create_table('contratos_notas_empenho_movimentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nota_id', sa.Uuid(), nullable=False),
    sa.Column('competencia_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('debito', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competencia_id'], ['contratos_competencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nota_id'], ['contratos_notas_empenho.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nota_id', 'competencia_id')
    )
    op.create_index(op.f('ix_contratos_notas_empenho_movimentos_competencia_id'), 'contratos_notas_empenho_movimentos', ['competencia_id'], unique=False)
    op.create_index(op.f('ix_contratos_notas_empenho_movimentos_nota_id'), 'contratos_notas_empenho_movimentos', ['nota_id'], unique=False)
    # Apontamentos e limites dos itens sob demanda na previsão
    op.create_table('contratos_previsoes_apontamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('previsao_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['contratos_itens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previsao_id'], ['contratos_previsoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('previsao_id', 'item_id', 'competencia')
    )
    op.create_index(op.f('ix_contratos_previsoes_apontamentos_item_id'), 'contratos_previsoes_apontamentos', ['item_id'], unique=False)
    op.create_index(op.f('ix_contratos_previsoes_apontamentos_previsao_id'), 'contratos_previsoes_apontamentos', ['previsao_id'], unique=False)
    op.create_table('contratos_previsoes_limites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('previsao_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantidade_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['contratos_itens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previsao_id'], ['contratos_previsoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('previsao_id', 'item_id')
    )
    op.create_index(op.f('ix_contratos_previsoes_limites_item_id'), 'contratos_previsoes_limites', ['item_id'], unique=False)
    op.create_index(op.f('ix_contratos_previsoes_limites_previsao_id'), 'contratos_previsoes_limites', ['previsao_id'], unique=False)
    # Rascunho da prorrogação (parecer e plano dos itens sob demanda)
    op.create_table('contratos_prorrogacoes_processos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('meses', sa.Integer(), nullable=True),
    sa.Column('regra_sob_demanda', sa.String(length=30), nullable=False),
    sa.Column('plano_sob_demanda', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('avaliacao_geral', sa.Text(), nullable=False),
    sa.Column('resumo_qualidade', sa.Text(), nullable=False),
    sa.Column('historico_ocorrencias', sa.Text(), nullable=False),
    sa.Column('reclamacoes', sa.Text(), nullable=False),
    sa.Column('atendimento_chamados', sa.Text(), nullable=False),
    sa.Column('parecer', sa.Text(), nullable=False),
    sa.Column('relatorio_anexo_id', sa.Uuid(), nullable=True),
    sa.Column('relatorio_hash', sa.String(length=64), nullable=False),
    sa.Column('prorrogacao_id', sa.Uuid(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prorrogacao_id'], ['contratos_prorrogacoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relatorio_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_prorrogacoes_processos_contrato_id'), 'contratos_prorrogacoes_processos', ['contrato_id'], unique=False)
    op.create_index('ux_contratos_prorrogacoes_processos_rascunho', 'contratos_prorrogacoes_processos', ['contrato_id'], unique=True, postgresql_where=sa.text("situacao = 'rascunho'"))
    # Itens e memórias do reajuste
    op.create_table('contratos_reajustes_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reajuste_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade_mensal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_unitario_atual', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('indice_percentual', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('valor_referencial', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_unitario_reajustado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['contratos_itens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reajuste_id'], ['contratos_reajustes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reajuste_id', 'item_id')
    )
    op.create_index(op.f('ix_contratos_reajustes_itens_item_id'), 'contratos_reajustes_itens', ['item_id'], unique=False)
    op.create_index(op.f('ix_contratos_reajustes_itens_reajuste_id'), 'contratos_reajustes_itens', ['reajuste_id'], unique=False)
    op.create_table('contratos_reajustes_memorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reajuste_id', sa.Uuid(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('pdf_anexo_id', sa.Uuid(), nullable=False),
    sa.Column('xlsx_anexo_id', sa.Uuid(), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pdf_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reajuste_id'], ['contratos_reajustes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['xlsx_anexo_id'], ['anexos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reajuste_id', 'versao')
    )
    op.create_index(op.f('ix_contratos_reajustes_memorias_reajuste_id'), 'contratos_reajustes_memorias', ['reajuste_id'], unique=False)
    # Ciências no parecer da prorrogação
    op.create_table('contratos_prorrogacoes_ciencias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('papel', sa.String(length=40), nullable=False),
    sa.Column('registrada_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['contratos_prorrogacoes_processos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processo_id', 'usuario_id')
    )
    op.create_index(op.f('ix_contratos_prorrogacoes_ciencias_processo_id'), 'contratos_prorrogacoes_ciencias', ['processo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Desfaz, apagando as tabelas na ordem inversa das dependências."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratos_prorrogacoes_ciencias_processo_id'), table_name='contratos_prorrogacoes_ciencias')
    op.drop_table('contratos_prorrogacoes_ciencias')
    op.drop_index(op.f('ix_contratos_reajustes_memorias_reajuste_id'), table_name='contratos_reajustes_memorias')
    op.drop_table('contratos_reajustes_memorias')
    op.drop_index(op.f('ix_contratos_reajustes_itens_reajuste_id'), table_name='contratos_reajustes_itens')
    op.drop_index(op.f('ix_contratos_reajustes_itens_item_id'), table_name='contratos_reajustes_itens')
    op.drop_table('contratos_reajustes_itens')
    op.drop_index('ux_contratos_prorrogacoes_processos_rascunho', table_name='contratos_prorrogacoes_processos', postgresql_where=sa.text("situacao = 'rascunho'"))
    op.drop_index(op.f('ix_contratos_prorrogacoes_processos_contrato_id'), table_name='contratos_prorrogacoes_processos')
    op.drop_table('contratos_prorrogacoes_processos')
    op.drop_index(op.f('ix_contratos_previsoes_limites_previsao_id'), table_name='contratos_previsoes_limites')
    op.drop_index(op.f('ix_contratos_previsoes_limites_item_id'), table_name='contratos_previsoes_limites')
    op.drop_table('contratos_previsoes_limites')
    op.drop_index(op.f('ix_contratos_previsoes_apontamentos_previsao_id'), table_name='contratos_previsoes_apontamentos')
    op.drop_index(op.f('ix_contratos_previsoes_apontamentos_item_id'), table_name='contratos_previsoes_apontamentos')
    op.drop_table('contratos_previsoes_apontamentos')
    op.drop_index(op.f('ix_contratos_notas_empenho_movimentos_nota_id'), table_name='contratos_notas_empenho_movimentos')
    op.drop_index(op.f('ix_contratos_notas_empenho_movimentos_competencia_id'), table_name='contratos_notas_empenho_movimentos')
    op.drop_table('contratos_notas_empenho_movimentos')
    op.drop_index(op.f('ix_contratos_competencias_notas_nota_id'), table_name='contratos_competencias_notas')
    op.drop_table('contratos_competencias_notas')
    op.drop_index(op.f('ix_contratos_competencias_memorias_competencia_id'), table_name='contratos_competencias_memorias')
    op.drop_table('contratos_competencias_memorias')
    op.drop_index(op.f('ix_contratos_competencias_itens_item_id'), table_name='contratos_competencias_itens')
    op.drop_index(op.f('ix_contratos_competencias_itens_competencia_id'), table_name='contratos_competencias_itens')
    op.drop_table('contratos_competencias_itens')
    op.drop_index(op.f('ix_contratos_competencias_documentos_competencia_id'), table_name='contratos_competencias_documentos')
    op.drop_table('contratos_competencias_documentos')
    op.drop_index(op.f('ix_contratos_competencias_ciencias_competencia_id'), table_name='contratos_competencias_ciencias')
    op.drop_table('contratos_competencias_ciencias')
    op.drop_index(op.f('ix_contratos_competencias_cadin_competencia_id'), table_name='contratos_competencias_cadin')
    op.drop_table('contratos_competencias_cadin')
    op.drop_table('contratos_competencias_avaliacoes')
    op.drop_index(op.f('ix_contratos_checklists_itens_checklist_id'), table_name='contratos_checklists_itens')
    op.drop_table('contratos_checklists_itens')
    op.drop_index(op.f('ix_contratos_alteracoes_itens_item_id'), table_name='contratos_alteracoes_itens')
    op.drop_index(op.f('ix_contratos_alteracoes_itens_alteracao_id'), table_name='contratos_alteracoes_itens')
    op.drop_table('contratos_alteracoes_itens')
    op.drop_index(op.f('ix_contratos_alteracoes_ciencias_alteracao_id'), table_name='contratos_alteracoes_ciencias')
    op.drop_table('contratos_alteracoes_ciencias')
    op.drop_index('ux_contratos_reajustes_rascunho', table_name='contratos_reajustes', postgresql_where=sa.text("situacao = 'rascunho'"))
    op.drop_index(op.f('ix_contratos_reajustes_contrato_id'), table_name='contratos_reajustes')
    op.drop_table('contratos_reajustes')
    op.drop_index(op.f('ix_contratos_prorrogacoes_contrato_id'), table_name='contratos_prorrogacoes')
    op.drop_table('contratos_prorrogacoes')
    op.drop_index(op.f('ix_contratos_previsoes_contrato_id'), table_name='contratos_previsoes')
    op.drop_table('contratos_previsoes')
    op.drop_index(op.f('ix_contratos_notas_empenho_contrato_id'), table_name='contratos_notas_empenho')
    op.drop_table('contratos_notas_empenho')
    op.drop_index(op.f('ix_contratos_formularios_contrato_id'), table_name='contratos_formularios')
    op.drop_table('contratos_formularios')
    op.drop_index(op.f('ix_contratos_competencias_contrato_id'), table_name='contratos_competencias')
    op.drop_table('contratos_competencias')
    op.drop_index(op.f('ix_contratos_checklists_contrato_id'), table_name='contratos_checklists')
    op.drop_table('contratos_checklists')
    op.drop_index('ux_contratos_alteracoes_em_andamento', table_name='contratos_alteracoes', postgresql_where=sa.text("situacao IN ('rascunho', 'aguardando_ciencias')"))
    op.drop_index(op.f('ix_contratos_alteracoes_contrato_id'), table_name='contratos_alteracoes')
    op.drop_table('contratos_alteracoes')
    op.drop_index(op.f('ix_contratos_modelos_tipo'), table_name='contratos_modelos')
    op.drop_table('contratos_modelos')
    # ### end Alembic commands ###
