# Criado por José Eduardo Santana Martins
# Este arquivo serve para criar as tabelas do Módulo RH (cadastro validado pela CGP, férias e licença-prêmio).
"""rh: alterações cadastrais, dados funcionais, afastamentos, eventos e parâmetros

- `rh_alteracoes_cadastrais`: alterações do perfil pendentes de validação da CGP (e o histórico);
- `rh_dados_funcionais`: campos exclusivos da CGP (autorizador, substituto, saldos);
- `rh_afastamentos` e `rh_afastamentos_eventos`: férias e licença-prêmio com histórico de status;
- `rh_parametros`: regras de agendamento (linha única, criada com os valores iniciais).

Revision ID: 6be74b4141cb
Revises: 0c11fdac4f46
Create Date: 2026-09-29 13:37:33.663989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificação da migração: esta revisão e a anterior
revision: str = '6be74b4141cb'
down_revision: Union[str, Sequence[str], None] = '0c11fdac4f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Cria as tabelas do Módulo RH e os parâmetros iniciais."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rh_parametros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minimo_dias_ferias', sa.Integer(), nullable=False),
    sa.Column('minimo_dias_lp', sa.Integer(), nullable=False),
    sa.Column('inicio_vedado_ferias', sa.JSON(), nullable=False),
    sa.Column('inicio_vedado_lp', sa.JSON(), nullable=False),
    sa.Column('antecedencia_minima_dias', sa.Integer(), nullable=False),
    sa.Column('prazo_cancelamento_dias', sa.Integer(), nullable=False),
    sa.Column('permite_emenda', sa.Boolean(), nullable=False),
    sa.Column('limite_alerta_setor', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_nome', sa.String(length=200), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name='rh_parametros_pkey')
    )
    op.create_table('rh_afastamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('solicitado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decidido_por_id', sa.Integer(), nullable=True),
    sa.Column('decidido_por_nome', sa.String(length=200), nullable=True),
    sa.Column('decidido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('substitui_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('pendente', 'aprovado', 'recusado', 'cancelado', 'gozado')", name='ck_rh_afastamentos_status'),
    sa.CheckConstraint("tipo IN ('ferias', 'licenca_premio')", name='ck_rh_afastamentos_tipo'),
    sa.CheckConstraint('fim >= inicio', name='ck_rh_afastamentos_periodo'),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['usuarios.id'], ondelete='SET NULL', name='rh_afastamentos_decidido_por_id_fkey'),
    sa.ForeignKeyConstraint(['substitui_id'], ['rh_afastamentos.id'], ondelete='SET NULL', name='rh_afastamentos_substitui_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE', name='rh_afastamentos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rh_afastamentos_pkey')
    )
    op.create_index('ix_rh_afastamentos_periodo', 'rh_afastamentos', ['inicio', 'fim'], unique=False)
    op.create_index('ix_rh_afastamentos_usuario_exercicio', 'rh_afastamentos', ['usuario_id', 'exercicio'], unique=False)
    op.create_table('rh_alteracoes_cadastrais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=40), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_proposto', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('solicitada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solicitada_por_id', sa.Integer(), nullable=True),
    sa.Column('solicitada_por_nome', sa.String(length=200), nullable=False),
    sa.Column('analisada_por_id', sa.Integer(), nullable=True),
    sa.Column('analisada_por_nome', sa.String(length=200), nullable=True),
    sa.Column('analisada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('valor_corrigido', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pendente', 'validada', 'recusada', 'substituida')", name='ck_rh_alteracoes_cadastrais_status'),
    sa.ForeignKeyConstraint(['analisada_por_id'], ['usuarios.id'], ondelete='SET NULL', name='rh_alteracoes_cadastrais_analisada_por_id_fkey'),
    sa.ForeignKeyConstraint(['solicitada_por_id'], ['usuarios.id'], ondelete='SET NULL', name='rh_alteracoes_cadastrais_solicitada_por_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE', name='rh_alteracoes_cadastrais_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rh_alteracoes_cadastrais_pkey')
    )
    op.create_index('ix_rh_alteracoes_cadastrais_usuario_status', 'rh_alteracoes_cadastrais', ['usuario_id', 'status'], unique=False)
    op.create_table('rh_dados_funcionais',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('autorizador_id', sa.Integer(), nullable=True),
    sa.Column('substituto_id', sa.Integer(), nullable=True),
    sa.Column('sem_superior', sa.Boolean(), nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=True),
    sa.Column('saldo_ferias_dias', sa.Integer(), nullable=False),
    sa.Column('saldo_lp_dias', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('atualizado_por_nome', sa.String(length=200), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ondelete='SET NULL', name='rh_dados_funcionais_atualizado_por_id_fkey'),
    sa.ForeignKeyConstraint(['autorizador_id'], ['usuarios.id'], ondelete='SET NULL', name='rh_dados_funcionais_autorizador_id_fkey'),
    sa.ForeignKeyConstraint(['substituto_id'], ['usuarios.id'], ondelete='SET NULL', name='rh_dados_funcionais_substituto_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE', name='rh_dados_funcionais_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('usuario_id', name='rh_dados_funcionais_pkey')
    )
    op.create_index('ix_rh_dados_funcionais_autorizador_id', 'rh_dados_funcionais', ['autorizador_id'], unique=False)
    op.create_table('rh_afastamentos_eventos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('afastamento_id', sa.Uuid(), nullable=False),
    sa.Column('de', sa.String(length=12), nullable=True),
    sa.Column('para', sa.String(length=12), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('autor_nome', sa.String(length=200), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['afastamento_id'], ['rh_afastamentos.id'], ondelete='CASCADE', name='rh_afastamentos_eventos_afastamento_id_fkey'),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='SET NULL', name='rh_afastamentos_eventos_autor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rh_afastamentos_eventos_pkey')
    )
    op.create_index('ix_rh_afastamentos_eventos_afastamento_id', 'rh_afastamentos_eventos', ['afastamento_id'], unique=False)
    # Parâmetros iniciais (a CGP ajusta na tela)
    op.execute(
        "INSERT INTO rh_parametros (id, minimo_dias_ferias, minimo_dias_lp, inicio_vedado_ferias, inicio_vedado_lp, "
        "antecedencia_minima_dias, prazo_cancelamento_dias, permite_emenda, limite_alerta_setor) "
        "VALUES (1, 5, 5, '[0]', '[0]', 30, 5, true, 3)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove as tabelas do Módulo RH (os dados se perdem)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rh_afastamentos_eventos_afastamento_id', table_name='rh_afastamentos_eventos')
    op.drop_table('rh_afastamentos_eventos')
    op.drop_index('ix_rh_dados_funcionais_autorizador_id', table_name='rh_dados_funcionais')
    op.drop_table('rh_dados_funcionais')
    op.drop_index('ix_rh_alteracoes_cadastrais_usuario_status', table_name='rh_alteracoes_cadastrais')
    op.drop_table('rh_alteracoes_cadastrais')
    op.drop_index('ix_rh_afastamentos_usuario_exercicio', table_name='rh_afastamentos')
    op.drop_index('ix_rh_afastamentos_periodo', table_name='rh_afastamentos')
    op.drop_table('rh_afastamentos')
    op.drop_table('rh_parametros')
    # ### end Alembic commands ###
