# Criado por José Eduardo Santana Martins
# Este arquivo serve para ampliar a quantidade medida da competência para 28 dígitos (contratos com quantidades acima de 100 milhões).
"""medição: quantidade medida com 28 dígitos (18 inteiros e 10 casas), como o schema de entrada

Antes eram 18 dígitos (8 inteiros): medir 100 milhões ou mais estourava a coluna ("numeric field overflow").
Só amplia a coluna; nenhum valor muda.

Revision ID: 78fca44765aa
Revises: 3f23277d8a5a
Create Date: 2026-10-01 18:03:51.502026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fca44765aa'
down_revision: Union[str, Sequence[str], None] = '3f23277d8a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos_competencias_itens', 'quantidade_medida',
               existing_type=sa.NUMERIC(precision=18, scale=10),
               type_=sa.Numeric(precision=28, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos_competencias_itens', 'quantidade_medida',
               existing_type=sa.Numeric(precision=28, scale=10),
               type_=sa.NUMERIC(precision=18, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###
