# Criado por José Eduardo Santana Martins
# Este arquivo serve para criar no banco as tabelas de setores e de controle de acesso (ACL).
"""setores e acl

Cria as tabelas de recursos e regras da ACL, setores e membros, e cadastra os recursos iniciais
(usuarios, setores, contratos, relatorios). Nomes em inglês, traduzidos depois pela migração
a1c3e5f7b9d2.

Revision ID: 7fb1ed802b9e
Revises: 8f8d17af10d8
Create Date: 2026-09-23 20:18:02.648695

"""
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb1ed802b9e'
down_revision: Union[str, Sequence[str], None] = '8f8d17af10d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Cria as tabelas da ACL e de setores e insere os recursos iniciais."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recursos protegidos (hoje `acl_recursos`)
    op.create_table('acl_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url_base', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ux_acl_resources_name_lower', 'acl_resources', [sa.literal_column('lower(name)')], unique=True)
    # Regras (hoje `acl_regras`) e as ligações com usuários e setores
    op.create_table('acl_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['acl_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_rules_resource_id'), 'acl_rules', ['resource_id'], unique=False)
    op.create_table('acl_rule_users',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['acl_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'user_id')
    )
    op.create_index(op.f('ix_acl_rule_users_user_id'), 'acl_rule_users', ['user_id'], unique=False)
    # Setores (hoje `setores`) e membros (hoje `membros_setor`)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('is_systemic', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['sectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_parent_id'), 'sectors', ['parent_id'], unique=False)
    op.create_index('ux_sectors_name_lower', 'sectors', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('acl_rule_sectors',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['acl_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'sector_id')
    )
    op.create_index(op.f('ix_acl_rule_sectors_sector_id'), 'acl_rule_sectors', ['sector_id'], unique=False)
    op.create_table('sector_members',
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sector_id', 'user_id')
    )
    op.create_index(op.f('ix_sector_members_user_id'), 'sector_members', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Recursos iniciais. "usuarios" e "setores" são usados pelos endpoints desses módulos.
    # `sa.table` descreve só as colunas usadas no insert (não depende dos modelos, que mudam com o tempo)
    resources = sa.table(
        "acl_resources",
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
        sa.column("description", sa.Text),
        sa.column("url_base", sa.String),
        sa.column("is_active", sa.Boolean),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(UTC)
    op.bulk_insert(
        resources,
        [
            {"name": "Usuários", "slug": "usuarios", "description": "Cadastro de usuários e perfis institucionais.", "url_base": "/usuarios", "is_active": True, "created_at": now, "updated_at": now},
            {"name": "Setores", "slug": "setores", "description": "Estrutura institucional e grupos de acesso.", "url_base": "/setores", "is_active": True, "created_at": now, "updated_at": now},
            {"name": "Contratos", "slug": "contratos", "description": "Gestão de contratos.", "url_base": "/contratos", "is_active": True, "created_at": now, "updated_at": now},
            {"name": "Relatórios", "slug": "relatorios", "description": "Relatórios gerenciais.", "url_base": "/relatorios", "is_active": True, "created_at": now, "updated_at": now},
        ],
    )


def downgrade() -> None:
    """Desfaz, apagando as tabelas na ordem inversa das dependências."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sector_members_user_id'), table_name='sector_members')
    op.drop_table('sector_members')
    op.drop_index(op.f('ix_acl_rule_sectors_sector_id'), table_name='acl_rule_sectors')
    op.drop_table('acl_rule_sectors')
    op.drop_index('ux_sectors_name_lower', table_name='sectors')
    op.drop_index(op.f('ix_sectors_parent_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_acl_rule_users_user_id'), table_name='acl_rule_users')
    op.drop_table('acl_rule_users')
    op.drop_index(op.f('ix_acl_rules_resource_id'), table_name='acl_rules')
    op.drop_table('acl_rules')
    op.drop_index('ux_acl_resources_name_lower', table_name='acl_resources')
    op.drop_table('acl_resources')
    # ### end Alembic commands ###
