# Criado por José Eduardo Santana Martins
# Este arquivo serve para permitir a exclusão lógica de versões inativas do formulário de avaliação.
"""formulario avaliacao exclusao logica

Revision ID: 8396ea301194
Revises: ab80abb2f10d
Create Date: 2026-10-02 22:03:09.415690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8396ea301194'
down_revision: Union[str, Sequence[str], None] = 'ab80abb2f10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos_formularios', sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos_formularios', 'excluido_em')
    # ### end Alembic commands ###
