# Criado por José Eduardo Santana Martins
# Este arquivo serve para criar o campo "documento com validade" no checklist e a validade do documento mensal.
"""checklist documentos com validade

Revision ID: ab80abb2f10d
Revises: 2183de7ec74a
Create Date: 2026-10-02 20:08:20.423075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab80abb2f10d'
down_revision: Union[str, Sequence[str], None] = '2183de7ec74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos_checklists_itens', sa.Column('com_validade', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('contratos_competencias_documentos', sa.Column('com_validade', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('contratos_competencias_documentos', sa.Column('validade_ate', sa.Date(), nullable=True))
    op.add_column('contratos_competencias_documentos', sa.Column('reaproveitado_de', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos_competencias_documentos', 'reaproveitado_de')
    op.drop_column('contratos_competencias_documentos', 'validade_ate')
    op.drop_column('contratos_competencias_documentos', 'com_validade')
    op.drop_column('contratos_checklists_itens', 'com_validade')
    # ### end Alembic commands ###
