# Criado por José Eduardo Santana Martins
# Este arquivo serve para criar o contador de versão do cadastro dos itens do contrato (base da sincronização das competências abertas).
"""contrato versao do cadastro dos itens

Revision ID: dd7999d97284
Revises: 8396ea301194
Create Date: 2026-10-02 22:25:55.906268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7999d97284'
down_revision: Union[str, Sequence[str], None] = '8396ea301194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('versao_cadastro', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'versao_cadastro')
    # ### end Alembic commands ###
