# Criado por José Eduardo Santana Martins
# Este arquivo serve para criar as tabelas de Contratações (ETP e TR) com árvore de itens, revisões e versionamento.
"""contratacoes ETP e TR com versionamento

Revision ID: e5b8c3d7a921
Revises: d4a7b2c6e815
Create Date: 2026-10-01 23:11:19.326155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5b8c3d7a921'
down_revision: Union[str, Sequence[str], None] = 'd4a7b2c6e815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratacoes_documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=3), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('processo', sa.String(length=100), nullable=False),
    sa.Column('link_sei', sa.String(length=500), nullable=True),
    sa.Column('situacao', sa.String(length=12), nullable=False),
    sa.Column('criador_id', sa.Integer(), nullable=True),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('contrato_id', sa.Uuid(), nullable=True),
    sa.Column('origem_sgi_id', sa.String(length=40), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_edicao_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("situacao IN ('rascunho', 'em_revisao', 'concluido')", name='ck_contratacoes_documentos_situacao'),
    sa.CheckConstraint("tipo IN ('etp', 'tr')", name='ck_contratacoes_documentos_tipo'),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['criador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_sgi_id')
    )
    op.create_index(op.f('ix_contratacoes_documentos_contrato_id'), 'contratacoes_documentos', ['contrato_id'], unique=False)
    op.create_index(op.f('ix_contratacoes_documentos_criador_id'), 'contratacoes_documentos', ['criador_id'], unique=False)
    op.create_table('contratacoes_historico_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('mudanca', sa.String(length=10), nullable=False),
    sa.Column('antes_html', sa.Text(), nullable=True),
    sa.Column('depois_html', sa.Text(), nullable=True),
    sa.Column('detalhe', sa.String(length=300), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('autor_nome', sa.String(length=200), nullable=False),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mudanca IN ('criou', 'editou', 'moveu', 'removeu', 'restaurou')", name='ck_contratacoes_historico_mudanca'),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['documento_id'], ['contratacoes_documentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contratacoes_historico_item_em', 'contratacoes_historico_itens', ['item_id', 'ocorrido_em'], unique=False)
    op.create_index(op.f('ix_contratacoes_historico_itens_documento_id'), 'contratacoes_historico_itens', ['documento_id'], unique=False)
    op.create_table('contratacoes_membros',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=8), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("papel IN ('editor', 'revisor')", name='ck_contratacoes_membros_papel'),
    sa.ForeignKeyConstraint(['documento_id'], ['contratacoes_documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'usuario_id', name='uq_contratacoes_membros_documento_usuario')
    )
    op.create_index(op.f('ix_contratacoes_membros_documento_id'), 'contratacoes_membros', ['documento_id'], unique=False)
    op.create_index(op.f('ix_contratacoes_membros_usuario_id'), 'contratacoes_membros', ['usuario_id'], unique=False)
    op.create_table('contratacoes_secoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('origem_sgi_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['contratacoes_documentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_sgi_id')
    )
    op.create_index(op.f('ix_contratacoes_secoes_documento_id'), 'contratacoes_secoes', ['documento_id'], unique=False)
    op.create_table('contratacoes_versoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('resumo', sa.String(length=500), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('autor_nome', sa.String(length=200), nullable=False),
    sa.Column('foto', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('criacao', 'manual', 'importacao', 'situacao', 'proposta', 'restauracao', 'migracao', 'sessao')", name='ck_contratacoes_versoes_tipo'),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['documento_id'], ['contratacoes_documentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'numero', name='uq_contratacoes_versoes_documento_numero')
    )
    op.create_index(op.f('ix_contratacoes_versoes_documento_id'), 'contratacoes_versoes', ['documento_id'], unique=False)
    op.create_table('contratacoes_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('secao_id', sa.Uuid(), nullable=False),
    sa.Column('pai_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('conteudo_html', sa.Text(), nullable=True),
    sa.Column('precisa_revisao', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('origem_sgi_id', sa.String(length=40), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('item', 'subitem', 'inciso', 'alinea', 'subsecao')", name='ck_contratacoes_itens_tipo'),
    sa.ForeignKeyConstraint(['pai_id'], ['contratacoes_itens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secao_id'], ['contratacoes_secoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_sgi_id')
    )
    op.create_index(op.f('ix_contratacoes_itens_secao_id'), 'contratacoes_itens', ['secao_id'], unique=False)
    op.create_index('ix_contratacoes_itens_secao_pai_ordem', 'contratacoes_itens', ['secao_id', 'pai_id', 'ordem'], unique=False)
    op.create_table('contratacoes_comentarios_importados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('id_externo', sa.String(length=60), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=False),
    sa.Column('iniciais', sa.String(length=20), nullable=True),
    sa.Column('comentado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('trecho', sa.Text(), nullable=False),
    sa.Column('abrange_mais', sa.Boolean(), nullable=False),
    sa.Column('origem_sgi_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['contratacoes_itens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_sgi_id')
    )
    op.create_index(op.f('ix_contratacoes_comentarios_importados_item_id'), 'contratacoes_comentarios_importados', ['item_id'], unique=False)
    op.create_table('contratacoes_revisoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('autor_nome', sa.String(length=200), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('conteudo_original', sa.Text(), nullable=False),
    sa.Column('conteudo_original_html', sa.Text(), nullable=True),
    sa.Column('conteudo_proposto', sa.Text(), nullable=True),
    sa.Column('conteudo_proposto_html', sa.Text(), nullable=True),
    sa.Column('aplicada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aplicada_por_id', sa.Integer(), nullable=True),
    sa.Column('aplicada_por_nome', sa.String(length=200), nullable=True),
    sa.Column('resolvida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolvida_por_nome', sa.String(length=200), nullable=True),
    sa.Column('origem_sgi_id', sa.String(length=40), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aplicada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['contratacoes_itens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_sgi_id')
    )
    op.create_index(op.f('ix_contratacoes_revisoes_item_id'), 'contratacoes_revisoes', ['item_id'], unique=False)
    op.create_table('contratacoes_tabela_tr',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('siafisico', sa.String(length=60), nullable=False),
    sa.Column('catser_catmat', sa.String(length=60), nullable=False),
    sa.Column('unidade', sa.String(length=60), nullable=False),
    sa.Column('quantidade_mensal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantidade_objeto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('origem_sgi_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['contratacoes_itens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_sgi_id')
    )
    op.create_index(op.f('ix_contratacoes_tabela_tr_item_id'), 'contratacoes_tabela_tr', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratacoes_tabela_tr_item_id'), table_name='contratacoes_tabela_tr')
    op.drop_table('contratacoes_tabela_tr')
    op.drop_index(op.f('ix_contratacoes_revisoes_item_id'), table_name='contratacoes_revisoes')
    op.drop_table('contratacoes_revisoes')
    op.drop_index(op.f('ix_contratacoes_comentarios_importados_item_id'), table_name='contratacoes_comentarios_importados')
    op.drop_table('contratacoes_comentarios_importados')
    op.drop_index('ix_contratacoes_itens_secao_pai_ordem', table_name='contratacoes_itens')
    op.drop_index(op.f('ix_contratacoes_itens_secao_id'), table_name='contratacoes_itens')
    op.drop_table('contratacoes_itens')
    op.drop_index(op.f('ix_contratacoes_versoes_documento_id'), table_name='contratacoes_versoes')
    op.drop_table('contratacoes_versoes')
    op.drop_index(op.f('ix_contratacoes_secoes_documento_id'), table_name='contratacoes_secoes')
    op.drop_table('contratacoes_secoes')
    op.drop_index(op.f('ix_contratacoes_membros_usuario_id'), table_name='contratacoes_membros')
    op.drop_index(op.f('ix_contratacoes_membros_documento_id'), table_name='contratacoes_membros')
    op.drop_table('contratacoes_membros')
    op.drop_index(op.f('ix_contratacoes_historico_itens_documento_id'), table_name='contratacoes_historico_itens')
    op.drop_index('ix_contratacoes_historico_item_em', table_name='contratacoes_historico_itens')
    op.drop_table('contratacoes_historico_itens')
    op.drop_index(op.f('ix_contratacoes_documentos_criador_id'), table_name='contratacoes_documentos')
    op.drop_index(op.f('ix_contratacoes_documentos_contrato_id'), table_name='contratacoes_documentos')
    op.drop_table('contratacoes_documentos')
    # ### end Alembic commands ###
